const ACTION_TYPES = {
  ONE_COIN: 'ONE',
  TWO_COINS: 'TWO',
  THREE_COINS: 'THREE',
  STEAL: 'STEAL',
  ASSASSINATE: 'ASSASSINATE',
  COUP: 'COUP',
  CHANGE_CARDS: 'CHANGE',

  START_GAME: 'START_GAME',
  ABANDON_GAME: 'ABANDON_GAME'
};

export default ACTION_TYPES;
